export const search=[
    {
        id:1,
        name:"Bhumika",
        age:22,
        gender:"Female",
        image:"https://media.istockphoto.com/id/1391534246/photo/portrait-of-happy-indian-girl-in-desert-village-india.webp?b=1&s=170667a&w=0&k=20&c=8F240KIqsrpCiRp0VKK31RAn7p7MbTZ-fPEn0EnKg4Q=",
        nationality:"Indian",
        occupation:"engineer",
        salary:"30LPA",
        mobile:"9267895678",
        place:"Delhi"
    },
    {
        id:2,
        name:"Chumika",
        age:20,
        gender:"Female",
        image:"https://images.pexels.com/photos/1391498/pexels-photo-1391498.jpeg?cs=srgb&dl=pexels-tu%E1%BA%A5n-ki%E1%BB%87t-jr-1391498.jpg&fm=jpg",
        nationality:"Indian",
        occupation:"engineer",
        salary:"30LPA",
        mobile:"8867895678",
        place:"Delhi"
    },
    {
        id:3,
        name:"Mika",
        age:22,
        gender:"Male",
        image:"https://img.indiaforums.com/media/640x0/16/1528-kushal-tandon.jpg",
        nationality:"Indian",
        occupation:"engineer",
        salary:"30LPA",
        mobile:"7867895678",
        place:"UP"
    },
    {
        id:4,
        name:"Bhumi",
        age:32,
        gender:"Female",
        image:"https://img.freepik.com/premium-photo/simple-looking-indian-girl-wearing-saree_5095-752.jpg",
        nationality:"Indian",
        occupation:"engineer",
        salary:"30LPA",
        mobile:"9777895678",
        place:"UK"
    },
    {
        id:5,
        name:"Popatlal",
        age:42,
        gender:"Male",
        image:"https://i.timesnowhindi.com/stories/tmkoc_popatlal.jpg",
        nationality:"Indian",
        occupation:"engineer",
        salary:"30LPA",
        mobile:"9867800678",
        place:"Delhi"
    },
    {
        id:6,
        name:"Surbhi",
        age:23,
        gender:"Female",
        image:"https://media.istockphoto.com/id/1391534246/photo/portrait-of-happy-indian-girl-in-desert-village-india.webp?b=1&s=170667a&w=0&k=20&c=8F240KIqsrpCiRp0VKK31RAn7p7MbTZ-fPEn0EnKg4Q=",
        nationality:"Indian",
        occupation:"engineer",
        salary:"30LPA",
        mobile:"9867895678",
        place:"Punjab"
    },
    {
        id:7,
        name:"Humik",
        age:26,
        gender:"Male",
        image:"https://img.indiaforums.com/media/640x0/16/1528-kushal-tandon.jpg",
        nationality:"Indian",
        occupation:"engineer",
        salary:"30LPA",
        mobile:"9867895678",
        place:"Chennai"
    }
]